### ISSUE TITLE
Crash in setup_general_cloud_optics

### ISSUE THREAD

**Issue by lguez** [ecmwf-ifs/ecrad#13]
Hello. We have a crash when we run ECRad, at line 183 of file `radiation_general_cloud_optics_data.F90`:
```
this%ssa       = matmul(mapping, mass_ext*ssa) / this%mass_ext
```
with message:
```
0: forrtl: severe (408): fort: (8):
  Attempt to fetch from allocatable variable MASS_EXT when it is not allocated
```
The code was compiled with ifort 19.0.4. There is no problem when we compile with gfortran 11. I looked at the crash with a debugger and I suspect this is a compiler bug. Could you please tell us which compilers and versions you have successfully used with ECRad?

**Comment by rjhogan** [comment]
We use ifort operationally in the IFS and --version returns:
ifort (IFORT) 2021.4.0 20210910

It would be useful to know if it is mass_ext that is not allocated or this%mass_ext. The first one would only not be allocated if there was a problem reading it from the file, but then the code should crash at that earlier point.

It could be that these three lines (182-184) are using the Fortran feature of automatically allocating the left hand side of array expressions according to the dimensions of the right hand side.  The previous line automatically allocates this%mass_ext - perhaps instead you should first manually allocate it via

allocate(this%mass_ext(size(mapping,1),size(mass_ext,2))

**Comment by lguez** [comment]
Thank you. With the debugger, I see that it is `this%mass_ext` which is not allocated. Yes, `this%mass_ext` should be automatically allocated at the previous line, and ifort 19 normally includes this Fortran 2003 feature. That is why I think it is a compiler bug. We will try to test this with a more recent version of ifort.

**Comment by lguez** [comment]
I have tested this with a more recent version of ifort: ifort 2021.9.0 20230302, and the problem is the same. It appears that, strangely, the problem does not occur if the code is compiled with option -qopenmp. I am convinced this is a compiler bug. We intend to file a report on this bug to Intel.

**Comment by reuterbal** [comment]
Since this appears to be a compiler bug I will close the issue
